### PR TITLE
Add support for 2.4.1

### PR DESCRIPTION
**Pull request by Techbrunch**
Remove Fixnum deprecation warning

### CODE REVIEW

**Comment by keichan34** [comment]
You can remove the `rbx-2` from travis.yml

**Comment by Techbrunch** [comment]
@keichan34 Done, the build is now passing

**Comment by keichan34** [comment]
Thanks!

**Comment by Techbrunch** [comment]
@keichan34 Can release a new version of the gem ?

**Comment by fernandoaleman** [comment]
@keichan34 Can you please release a new version of the gem with the updated fix for Fixnum?

**Pull request merged**
